"""empty message

Revision ID: 862250184e2e
Revises: e0cb4f439918
Create Date: 2020-06-04 20:33:16.255054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862250184e2e'
down_revision = 'e0cb4f439918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_views',
    sa.Column('amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_views')
    # ### end Alembic commands ###
